default_platform(:android)

platform :android do
  lane :release_to_store do

    def redirect_stdout_to_file(filename)
      original_stdout = $stdout.clone
      original_stderr = $stderr.clone
      $stderr.reopen File.new(filename, 'w')
      $stdout.reopen File.new(filename, 'w')
      yield
    ensure
      $stdout.reopen original_stdout
      $stderr.reopen original_stderr
    end

    if ENV["GITHUB_EVENT_NAME"] == "pull_request"
      event_data = JSON.parse(File.read(ENV["GITHUB_EVENT_PATH"]))
      pr_id = event_data["number"]
      UI.message("Running for PR ##{pr_id}")
    end

    branch_name = ENV['GITHUB_REF_NAME']
    if branch_name == "master"
      commit_info = sh("git log --merges -n 1 --pretty=format:'%s'", log: false).strip
      if commit_info =~ /Merge pull request #(\d+) from (.+)/
        pr_id = $1
        branch_name = $2
        UI.message("Merged PR ##{pr_id} from branch: #{branch_name}")
      end
    end
    

    UI.message("Started on branch #{branch_name}, PR #{pr_id}")

    begin
      redirect_stdout_to_file('logs_for_instabug.txt') do
        # This should fail of course
        upload_to_play_store(
          aab: "app/build/outputs/bundle/release/app-release.aab",
          json_key: "fastlane/google-play.json",
          track: "internal"
        )
      end
    ensure
      logs = File.read("logs_for_instabug.txt")
      p "Captured logs: #{logs}"
      UI.message("Using UI: #{logs}")
    end
  end
end
