name: Android Release

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Decrypt Play Store credentials
        run: |
          echo "${{ secrets.GOOGLE_PLAY_JSON }}" > fastlane/google-play.json

      - name: Run Fastlane
        run: bundle exec fastlane release_to_store
